## Applying classification by neural network on iris data set

In [1]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
import numpy as np

In [2]:
# import some data to play with
iris = datasets.load_iris()

In [3]:
predictor = iris.data
target = iris.target

In [4]:
predictor

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
predictor1=predictor.reshape(predictor.shape[0]*predictor.shape[1])
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
data_set=np.column_stack((predictor,target))

In [7]:
np.random.shuffle(data_set)
training, test = data_set[:120,:], data_set[120:,:]

In [8]:
train_x = training[:,:4]
train_y = training[:,4]
test_x = test[:,:4]
test_y = test[:,4]

creating a neural network for classification

In [9]:
import torch.nn as nn
import torch.nn.functional as F
#our class must extend nn.Module
class MyClassifier(nn.Module):
    def __init__(self):
        super(MyClassifier,self).__init__()
        #Our network consists of 3 layers. 1 input, 1 hidden and 1 output layer
        #This applies Linear transformation to input data. 
        self.layer1 = nn.Linear(4,3)
        self.layer2 = nn.Linear(3,3)
    
    
    #This must be implemented
    def forward(self,x):
        #of the first layer
        x = self.layer1(x)
        #Activation function is Relu. Feel free to experiment with this
        x = F.tanh(x)
        #This produces output
        x = self.layer2(x)    
        return x
        
    #This function takes an input and predicts the class, (0 or 1)        
    def predict(self,x):
        #Apply softmax to output. 
        prediction = F.softmax(self.forward(x))
        ans = []
        #Pick the class with maximum weight
        for t in prediction:
            #print("\nt0 :- ",t[0])
            #print("\nt1 :- ",t[1])
            #print("\nt2 :-",t[2])
            if t[0]>t[1]:
                if(t[0]>t[2]):
                    ans.append(0)
                else:
                    ans.append(2)
            elif(t[1]>t[2]):
                ans.append(1)
            else:
                ans.append(2)
        return torch.tensor(ans)

In [10]:
import torch
#Initialize the model        
model = MyClassifier()
#Define loss criterion
criterion = nn.CrossEntropyLoss()
#Define the optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [11]:
#convert the array into pytorch object
train_x = torch.from_numpy(train_x).type(torch.FloatTensor)
train_y = torch.from_numpy(train_y).type(torch.LongTensor)
test_x = torch.from_numpy(test_x).type(torch.FloatTensor)
test_y = torch.from_numpy(test_y).type(torch.LongTensor)

In [12]:
train_x.requires_grad = True
test_x.requires_grad = True

In [13]:
train_x

tensor([[5.7000, 2.9000, 4.2000, 1.3000],
        [6.7000, 3.3000, 5.7000, 2.1000],
        [6.8000, 2.8000, 4.8000, 1.4000],
        [6.3000, 2.5000, 5.0000, 1.9000],
        [5.5000, 2.6000, 4.4000, 1.2000],
        [7.1000, 3.0000, 5.9000, 2.1000],
        [5.9000, 3.0000, 4.2000, 1.5000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [7.7000, 2.6000, 6.9000, 2.3000],
        [7.7000, 2.8000, 6.7000, 2.0000],
        [5.7000, 3.8000, 1.7000, 0.3000],
        [6.2000, 2.8000, 4.8000, 1.8000],
        [4.9000, 2.4000, 3.3000, 1.0000],
        [6.2000, 3.4000, 5.4000, 2.3000],
        [6.3000, 2.3000, 4.4000, 1.3000],
        [6.0000, 2.2000, 4.0000, 1.0000],
        [6.8000, 3.2000, 5.9000, 2.3000],
        [4.8000, 3.0000, 1.4000, 0.1000],
        [5.0000, 3.3000, 1.4000, 0.2000],
        [6.7000, 3.1000, 5.6000, 2.4000],
        [5.5000, 2.3000, 4.0000, 1.3000],
        [6.4000, 2.8000, 5.6000, 2.2000],
        [6.7000, 3.1000, 4.4000, 1.4000],
        [5.4000, 3.0000, 4.5000, 1

In [14]:
#Number of epochs
epochs = 10000
#List to store losses
losses = []
for i in range(epochs):
    #Precit the output for Given input
    y_pred = model.forward(train_x)
    #Clear the previous gradients
    optimizer.zero_grad()
    #Compute Cross entropy loss
    loss = criterion(y_pred,train_y)
    #Add loss to the list
    losses.append(loss.item())
    #Compute gradients
    loss.backward()
    #Adjust weights
    optimizer.step()
    print('epoch {}, loss {} '.format(i, loss.item()))

/usr/local/lib/python3.7/site-packages/torch/nn/functional.py:1340: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


epoch 0, loss 1.0597865581512451 
epoch 1, loss 1.0371023416519165 
epoch 2, loss 1.0128134489059448 
epoch 3, loss 0.9871377348899841 
epoch 4, loss 0.9609096646308899 
epoch 5, loss 0.9351760745048523 
epoch 6, loss 0.9109895825386047 
epoch 7, loss 0.889139711856842 
epoch 8, loss 0.8699211478233337 
epoch 9, loss 0.8531744480133057 
epoch 10, loss 0.8386024236679077 
epoch 11, loss 0.8260329961776733 
epoch 12, loss 0.8152554631233215 
epoch 13, loss 0.8057177066802979 
epoch 14, loss 0.7966161966323853 
epoch 15, loss 0.7872516512870789 
epoch 16, loss 0.777226984500885 
epoch 17, loss 0.7664312720298767 
epoch 18, loss 0.7549733519554138 
epoch 19, loss 0.7431107759475708 
epoch 20, loss 0.73118656873703 
epoch 21, loss 0.719552218914032 
epoch 22, loss 0.7085004448890686 
epoch 23, loss 0.6982083916664124 
epoch 24, loss 0.6887238025665283 
epoch 25, loss 0.6799793839454651 
epoch 26, loss 0.6718379855155945 
epoch 27, loss 0.6641415953636169 
epoch 28, loss 0.6567449569702148 


epoch 240, loss 0.12978096306324005 
epoch 241, loss 0.12914212048053741 
epoch 242, loss 0.1285116821527481 
epoch 243, loss 0.12788940966129303 
epoch 244, loss 0.12727521359920502 
epoch 245, loss 0.1266689896583557 
epoch 246, loss 0.12607060372829437 
epoch 247, loss 0.12547987699508667 
epoch 248, loss 0.12489668279886246 
epoch 249, loss 0.12432089447975159 
epoch 250, loss 0.12375244498252869 
epoch 251, loss 0.12319109588861465 
epoch 252, loss 0.1226368397474289 
epoch 253, loss 0.12208949774503708 
epoch 254, loss 0.12154898047447205 
epoch 255, loss 0.12101514637470245 
epoch 256, loss 0.12048783898353577 
epoch 257, loss 0.11996708065271378 
epoch 258, loss 0.11945268511772156 
epoch 259, loss 0.11894452571868896 
epoch 260, loss 0.11844254285097122 
epoch 261, loss 0.11794659495353699 
epoch 262, loss 0.11745660752058029 
epoch 263, loss 0.11697248369455338 
epoch 264, loss 0.11649414896965027 
epoch 265, loss 0.11602146178483963 
epoch 266, loss 0.11555435508489609 
epoc

epoch 630, loss 0.06484165042638779 
epoch 631, loss 0.0648028627038002 
epoch 632, loss 0.06476421654224396 
epoch 633, loss 0.06472574174404144 
epoch 634, loss 0.06468740850687027 
epoch 635, loss 0.06464923173189163 
epoch 636, loss 0.06461119651794434 
epoch 637, loss 0.06457332521677017 
epoch 638, loss 0.06453558802604675 
epoch 639, loss 0.06449803709983826 
epoch 640, loss 0.06446059793233871 
epoch 641, loss 0.06442330032587051 
epoch 642, loss 0.06438613682985306 
epoch 643, loss 0.06434915959835052 
epoch 644, loss 0.06431228667497635 
epoch 645, loss 0.06427560746669769 
epoch 646, loss 0.06423904746770859 
epoch 647, loss 0.06420257687568665 
epoch 648, loss 0.06416629999876022 
epoch 649, loss 0.06413013488054276 
epoch 650, loss 0.06409411132335663 
epoch 651, loss 0.06405825167894363 
epoch 652, loss 0.06402251124382019 
epoch 653, loss 0.0639868751168251 
epoch 654, loss 0.06395142525434494 
epoch 655, loss 0.06391605734825134 
epoch 656, loss 0.06388088315725327 
epo

epoch 886, loss 0.05814504250884056 
epoch 887, loss 0.05812700465321541 
epoch 888, loss 0.05810900032520294 
epoch 889, loss 0.05809104070067406 
epoch 890, loss 0.05807311460375786 
epoch 891, loss 0.05805525556206703 
epoch 892, loss 0.0580374076962471 
epoch 893, loss 0.05801960453391075 
epoch 894, loss 0.058001868426799774 
epoch 895, loss 0.0579841323196888 
epoch 896, loss 0.0579664520919323 
epoch 897, loss 0.05794882774353027 
epoch 898, loss 0.05793122574687004 
epoch 899, loss 0.057913679629564285 
epoch 900, loss 0.05789615213871002 
epoch 901, loss 0.05787866190075874 
epoch 902, loss 0.057861220091581345 
epoch 903, loss 0.05784381181001663 
epoch 904, loss 0.057826459407806396 
epoch 905, loss 0.057809121906757355 
epoch 906, loss 0.05779184028506279 
epoch 907, loss 0.05777459219098091 
epoch 908, loss 0.05775737762451172 
epoch 909, loss 0.057740192860364914 
epoch 910, loss 0.057723090052604675 
epoch 911, loss 0.05770598351955414 
epoch 912, loss 0.0576889291405677

epoch 1134, loss 0.05468134582042694 
epoch 1135, loss 0.05467085540294647 
epoch 1136, loss 0.05466042086482048 
epoch 1137, loss 0.05464997515082359 
epoch 1138, loss 0.05463957041501999 
epoch 1139, loss 0.054629191756248474 
epoch 1140, loss 0.05461883544921875 
epoch 1141, loss 0.05460848659276962 
epoch 1142, loss 0.05459816753864288 
epoch 1143, loss 0.05458788946270943 
epoch 1144, loss 0.054577626287937164 
epoch 1145, loss 0.05456739291548729 
epoch 1146, loss 0.05455714464187622 
epoch 1147, loss 0.05454699695110321 
epoch 1148, loss 0.05453679710626602 
epoch 1149, loss 0.05452663451433182 
epoch 1150, loss 0.054516516625881195 
epoch 1151, loss 0.054506439715623856 
epoch 1152, loss 0.05449635908007622 
epoch 1153, loss 0.05448632687330246 
epoch 1154, loss 0.054476309567689896 
epoch 1155, loss 0.05446629598736763 
epoch 1156, loss 0.054456308484077454 
epoch 1157, loss 0.05444636568427086 
epoch 1158, loss 0.05443643033504486 
epoch 1159, loss 0.05442654341459274 
epoch 

epoch 1359, loss 0.052880506962537766 
epoch 1360, loss 0.052874691784381866 
epoch 1361, loss 0.05286882445216179 
epoch 1362, loss 0.052863072603940964 
epoch 1363, loss 0.05285731330513954 
epoch 1364, loss 0.05285154655575752 
epoch 1365, loss 0.05284576490521431 
epoch 1366, loss 0.052840057760477066 
epoch 1367, loss 0.05283432826399803 
epoch 1368, loss 0.05282864719629288 
epoch 1369, loss 0.052822940051555634 
epoch 1370, loss 0.05281730741262436 
epoch 1371, loss 0.05281165987253189 
epoch 1372, loss 0.05280601605772972 
epoch 1373, loss 0.05280037969350815 
epoch 1374, loss 0.05279476195573807 
epoch 1375, loss 0.05278915539383888 
epoch 1376, loss 0.05278361216187477 
epoch 1377, loss 0.052778057754039764 
epoch 1378, loss 0.05277251824736595 
epoch 1379, loss 0.05276699736714363 
epoch 1380, loss 0.05276143550872803 
epoch 1381, loss 0.052755992859601974 
epoch 1382, loss 0.05275044962763786 
epoch 1383, loss 0.05274499952793121 
epoch 1384, loss 0.05273958295583725 
epoch

epoch 1595, loss 0.05186764523386955 
epoch 1596, loss 0.05186454579234123 
epoch 1597, loss 0.05186150595545769 
epoch 1598, loss 0.051858484745025635 
epoch 1599, loss 0.05185547098517418 
epoch 1600, loss 0.051852382719516754 
epoch 1601, loss 0.051849402487277985 
epoch 1602, loss 0.051846351474523544 
epoch 1603, loss 0.05184335634112358 
epoch 1604, loss 0.05184037238359451 
epoch 1605, loss 0.05183735862374306 
epoch 1606, loss 0.051834411919116974 
epoch 1607, loss 0.05183142423629761 
epoch 1608, loss 0.051828447729349136 
epoch 1609, loss 0.05182551220059395 
epoch 1610, loss 0.051822543144226074 
epoch 1611, loss 0.05181966349482536 
epoch 1612, loss 0.05181672051548958 
epoch 1613, loss 0.051813747733831406 
epoch 1614, loss 0.051810864359140396 
epoch 1615, loss 0.05180793255567551 
epoch 1616, loss 0.05180506408214569 
epoch 1617, loss 0.0518021397292614 
epoch 1618, loss 0.05179929360747337 
epoch 1619, loss 0.05179636925458908 
epoch 1620, loss 0.051793500781059265 
epo

epoch 1871, loss 0.05126368999481201 
epoch 1872, loss 0.05126212164759636 
epoch 1873, loss 0.0512605682015419 
epoch 1874, loss 0.05125904828310013 
epoch 1875, loss 0.05125751718878746 
epoch 1876, loss 0.0512559749186039 
epoch 1877, loss 0.05125449597835541 
epoch 1878, loss 0.05125299468636513 
epoch 1879, loss 0.051251497119665146 
epoch 1880, loss 0.051249969750642776 
epoch 1881, loss 0.0512484572827816 
epoch 1882, loss 0.05124697834253311 
epoch 1883, loss 0.05124546214938164 
epoch 1884, loss 0.05124395713210106 
epoch 1885, loss 0.05124247819185257 
epoch 1886, loss 0.05124097689986229 
epoch 1887, loss 0.0512395054101944 
epoch 1888, loss 0.0512380376458168 
epoch 1889, loss 0.051236528903245926 
epoch 1890, loss 0.05123506858944893 
epoch 1891, loss 0.05123359337449074 
epoch 1892, loss 0.05123213678598404 
epoch 1893, loss 0.05123062804341316 
epoch 1894, loss 0.05122917890548706 
epoch 1895, loss 0.05122774466872215 
epoch 1896, loss 0.051226284354925156 
epoch 1897, l

epoch 2135, loss 0.05095282569527626 
epoch 2136, loss 0.05095188319683075 
epoch 2137, loss 0.05095099285244942 
epoch 2138, loss 0.05095004662871361 
epoch 2139, loss 0.050949182361364365 
epoch 2140, loss 0.050948262214660645 
epoch 2141, loss 0.05094735324382782 
epoch 2142, loss 0.0509464405477047 
epoch 2143, loss 0.050945598632097244 
epoch 2144, loss 0.05094471201300621 
epoch 2145, loss 0.0509437657892704 
epoch 2146, loss 0.05094287544488907 
epoch 2147, loss 0.05094202607870102 
epoch 2148, loss 0.05094112828373909 
epoch 2149, loss 0.050940223038196564 
epoch 2150, loss 0.05093934014439583 
epoch 2151, loss 0.05093840882182121 
epoch 2152, loss 0.05093758925795555 
epoch 2153, loss 0.05093668773770332 
epoch 2154, loss 0.05093584209680557 
epoch 2155, loss 0.05093491077423096 
epoch 2156, loss 0.05093403905630112 
epoch 2157, loss 0.05093317851424217 
epoch 2158, loss 0.05093230679631233 
epoch 2159, loss 0.05093143507838249 
epoch 2160, loss 0.05093057081103325 
epoch 2161

epoch 2415, loss 0.05074664577841759 
epoch 2416, loss 0.05074603110551834 
epoch 2417, loss 0.05074542388319969 
epoch 2418, loss 0.05074483901262283 
epoch 2419, loss 0.05074422061443329 
epoch 2420, loss 0.05074365437030792 
epoch 2421, loss 0.05074303597211838 
epoch 2422, loss 0.05074239894747734 
epoch 2423, loss 0.05074179545044899 
epoch 2424, loss 0.05074120685458183 
epoch 2425, loss 0.05074058473110199 
epoch 2426, loss 0.05074000358581543 
epoch 2427, loss 0.05073942244052887 
epoch 2428, loss 0.0507388673722744 
epoch 2429, loss 0.05073820799589157 
epoch 2430, loss 0.0507376454770565 
epoch 2431, loss 0.05073706805706024 
epoch 2432, loss 0.05073641985654831 
epoch 2433, loss 0.05073587968945503 
epoch 2434, loss 0.0507352352142334 
epoch 2435, loss 0.05073468014597893 
epoch 2436, loss 0.050734084099531174 
epoch 2437, loss 0.05073348060250282 
epoch 2438, loss 0.050732873380184174 
epoch 2439, loss 0.050732314586639404 
epoch 2440, loss 0.050731729716062546 
epoch 2441,

epoch 2699, loss 0.05061814561486244 
epoch 2700, loss 0.050630442798137665 
epoch 2701, loss 0.050651710480451584 
epoch 2702, loss 0.05068402364850044 
epoch 2703, loss 0.050735726952552795 
epoch 2704, loss 0.05079662427306175 
epoch 2705, loss 0.050868384540081024 
epoch 2706, loss 0.050888195633888245 
epoch 2707, loss 0.05085219815373421 
epoch 2708, loss 0.05073218047618866 
epoch 2709, loss 0.050624780356884 
epoch 2710, loss 0.050596244633197784 
epoch 2711, loss 0.05064762383699417 
epoch 2712, loss 0.05071338266134262 
epoch 2713, loss 0.05071760714054108 
epoch 2714, loss 0.050664059817790985 
epoch 2715, loss 0.05060365051031113 
epoch 2716, loss 0.05059628561139107 
epoch 2717, loss 0.0506337471306324 
epoch 2718, loss 0.05066104978322983 
epoch 2719, loss 0.050647374242544174 
epoch 2720, loss 0.05060812085866928 
epoch 2721, loss 0.0505894273519516 
epoch 2722, loss 0.050604455173015594 
epoch 2723, loss 0.05062586069107056 
epoch 2724, loss 0.05062554031610489 
epoch 2

epoch 2962, loss 0.05049300938844681 
epoch 2963, loss 0.05049842223525047 
epoch 2964, loss 0.050502143800258636 
epoch 2965, loss 0.050498709082603455 
epoch 2966, loss 0.05049262195825577 
epoch 2967, loss 0.05049087107181549 
epoch 2968, loss 0.05049384385347366 
epoch 2969, loss 0.05049608647823334 
epoch 2970, loss 0.05049416050314903 
epoch 2971, loss 0.050490375608205795 
epoch 2972, loss 0.05048888549208641 
epoch 2973, loss 0.05049031227827072 
epoch 2974, loss 0.050491705536842346 
epoch 2975, loss 0.05049069970846176 
epoch 2976, loss 0.05048837512731552 
epoch 2977, loss 0.050487007945775986 
epoch 2978, loss 0.05048751458525658 
epoch 2979, loss 0.05048828572034836 
epoch 2980, loss 0.05048790201544762 
epoch 2981, loss 0.050486400723457336 
epoch 2982, loss 0.05048520117998123 
epoch 2983, loss 0.05048512667417526 
epoch 2984, loss 0.05048544704914093 
epoch 2985, loss 0.05048535019159317 
epoch 2986, loss 0.05048447474837303 
epoch 2987, loss 0.05048350989818573 
epoch 

epoch 3220, loss 0.05040579289197922 
epoch 3221, loss 0.05040612071752548 
epoch 3222, loss 0.050405777990818024 
epoch 3223, loss 0.05040479451417923 
epoch 3224, loss 0.050403907895088196 
epoch 3225, loss 0.05040362849831581 
epoch 3226, loss 0.05040375888347626 
epoch 3227, loss 0.05040372535586357 
epoch 3228, loss 0.05040327087044716 
epoch 3229, loss 0.05040258169174194 
epoch 3230, loss 0.050401993095874786 
epoch 3231, loss 0.05040174722671509 
epoch 3232, loss 0.05040162056684494 
epoch 3233, loss 0.05040150508284569 
epoch 3234, loss 0.05040112882852554 
epoch 3235, loss 0.05040055885910988 
epoch 3236, loss 0.05040013790130615 
epoch 3237, loss 0.05039984732866287 
epoch 3238, loss 0.050399694591760635 
epoch 3239, loss 0.05039941519498825 
epoch 3240, loss 0.050399087369441986 
epoch 3241, loss 0.05039864405989647 
epoch 3242, loss 0.05039830505847931 
epoch 3243, loss 0.05039798468351364 
epoch 3244, loss 0.05039772763848305 
epoch 3245, loss 0.05039745569229126 
epoch 3

epoch 3501, loss 0.050323568284511566 
epoch 3502, loss 0.050323329865932465 
epoch 3503, loss 0.05032310634851456 
epoch 3504, loss 0.05032280832529068 
epoch 3505, loss 0.0503225177526474 
epoch 3506, loss 0.050322260707616806 
epoch 3507, loss 0.05032198131084442 
epoch 3508, loss 0.05032173916697502 
epoch 3509, loss 0.05032149702310562 
epoch 3510, loss 0.050321221351623535 
epoch 3511, loss 0.05032091215252876 
epoch 3512, loss 0.050320666283369064 
epoch 3513, loss 0.050320401787757874 
epoch 3514, loss 0.0503200888633728 
epoch 3515, loss 0.050319842994213104 
epoch 3516, loss 0.05031956359744072 
epoch 3517, loss 0.050319332629442215 
epoch 3518, loss 0.05031901225447655 
epoch 3519, loss 0.050318822264671326 
epoch 3520, loss 0.05031853914260864 
epoch 3521, loss 0.05031824856996536 
epoch 3522, loss 0.05031798779964447 
epoch 3523, loss 0.050317712128162384 
epoch 3524, loss 0.05031745880842209 
epoch 3525, loss 0.05031715705990791 
epoch 3526, loss 0.0503169409930706 
epoch

epoch 3785, loss 0.050252076238393784 
epoch 3786, loss 0.05025181546807289 
epoch 3787, loss 0.05025160685181618 
epoch 3788, loss 0.05025136470794678 
epoch 3789, loss 0.05025113746523857 
epoch 3790, loss 0.050250887870788574 
epoch 3791, loss 0.05025065317749977 
epoch 3792, loss 0.05025036633014679 
epoch 3793, loss 0.05025019496679306 
epoch 3794, loss 0.05024997144937515 
epoch 3795, loss 0.05024968460202217 
epoch 3796, loss 0.05024946853518486 
epoch 3797, loss 0.05024922639131546 
epoch 3798, loss 0.050248995423316956 
epoch 3799, loss 0.05024878680706024 
epoch 3800, loss 0.05024855211377144 
epoch 3801, loss 0.05024826154112816 
epoch 3802, loss 0.05024803429841995 
epoch 3803, loss 0.050247788429260254 
epoch 3804, loss 0.05024755001068115 
epoch 3805, loss 0.050247352570295334 
epoch 3806, loss 0.050247084349393845 
epoch 3807, loss 0.05024687573313713 
epoch 3808, loss 0.05024661496281624 
epoch 3809, loss 0.05024642497301102 
epoch 3810, loss 0.050246160477399826 
epoch

epoch 4068, loss 0.05018886551260948 
epoch 4069, loss 0.05018864944577217 
epoch 4070, loss 0.050188418477773666 
epoch 4071, loss 0.05018818378448486 
epoch 4072, loss 0.05018799379467964 
epoch 4073, loss 0.05018775537610054 
epoch 4074, loss 0.05018753185868263 
epoch 4075, loss 0.050187334418296814 
epoch 4076, loss 0.05018717050552368 
epoch 4077, loss 0.050186946988105774 
epoch 4078, loss 0.05018666759133339 
epoch 4079, loss 0.05018645524978638 
epoch 4080, loss 0.05018628388643265 
epoch 4081, loss 0.050186000764369965 
epoch 4082, loss 0.05018586665391922 
epoch 4083, loss 0.05018563196063042 
epoch 4084, loss 0.05018540844321251 
epoch 4085, loss 0.050185199826955795 
epoch 4086, loss 0.05018499866127968 
epoch 4087, loss 0.05018478259444237 
epoch 4088, loss 0.050184570252895355 
epoch 4089, loss 0.05018434301018715 
epoch 4090, loss 0.05018417164683342 
epoch 4091, loss 0.05018395930528641 
epoch 4092, loss 0.050183773040771484 
epoch 4093, loss 0.05018356814980507 
epoch

epoch 4349, loss 0.050176944583654404 
epoch 4350, loss 0.05018017068505287 
epoch 4351, loss 0.05015674978494644 
epoch 4352, loss 0.050134263932704926 
epoch 4353, loss 0.05013629049062729 
epoch 4354, loss 0.05015339329838753 
epoch 4355, loss 0.05016044154763222 
epoch 4356, loss 0.05014973506331444 
epoch 4357, loss 0.05013454705476761 
epoch 4358, loss 0.050131894648075104 
epoch 4359, loss 0.050140876322984695 
epoch 4360, loss 0.0501473993062973 
epoch 4361, loss 0.050143491476774216 
epoch 4362, loss 0.05013403668999672 
epoch 4363, loss 0.05013005807995796 
epoch 4364, loss 0.050133995711803436 
epoch 4365, loss 0.05013888329267502 
epoch 4366, loss 0.05013835057616234 
epoch 4367, loss 0.050133027136325836 
epoch 4368, loss 0.05012926086783409 
epoch 4369, loss 0.05013019219040871 
epoch 4370, loss 0.05013331398367882 
epoch 4371, loss 0.05013420805335045 
epoch 4372, loss 0.05013173446059227 
epoch 4373, loss 0.05012873187661171 
epoch 4374, loss 0.05012814328074455 
epoch 

epoch 4624, loss 0.05008310079574585 
epoch 4625, loss 0.050082698464393616 
epoch 4626, loss 0.05008235201239586 
epoch 4627, loss 0.05008218064904213 
epoch 4628, loss 0.05008215084671974 
epoch 4629, loss 0.05008211359381676 
epoch 4630, loss 0.05008191615343094 
epoch 4631, loss 0.050081606954336166 
epoch 4632, loss 0.05008134990930557 
epoch 4633, loss 0.05008111149072647 
epoch 4634, loss 0.05008099600672722 
epoch 4635, loss 0.050080880522727966 
epoch 4636, loss 0.05008072033524513 
epoch 4637, loss 0.05008052662014961 
epoch 4638, loss 0.05008026584982872 
epoch 4639, loss 0.050080105662345886 
epoch 4640, loss 0.05007991939783096 
epoch 4641, loss 0.05007976293563843 
epoch 4642, loss 0.05007960647344589 
epoch 4643, loss 0.05007942393422127 
epoch 4644, loss 0.050079260021448135 
epoch 4645, loss 0.05007902905344963 
epoch 4646, loss 0.0500788614153862 
epoch 4647, loss 0.05007869377732277 
epoch 4648, loss 0.05007854476571083 
epoch 4649, loss 0.050078365951776505 
epoch 4

epoch 4908, loss 0.0500352568924427 
epoch 4909, loss 0.050035085529088974 
epoch 4910, loss 0.050034914165735245 
epoch 4911, loss 0.0500347763299942 
epoch 4912, loss 0.05003459006547928 
epoch 4913, loss 0.05003444850444794 
epoch 4914, loss 0.05003427341580391 
epoch 4915, loss 0.05003410577774048 
epoch 4916, loss 0.05003396049141884 
epoch 4917, loss 0.05003378540277481 
epoch 4918, loss 0.05003362149000168 
epoch 4919, loss 0.05003349110484123 
epoch 4920, loss 0.05003325268626213 
epoch 4921, loss 0.05003313720226288 
epoch 4922, loss 0.05003296583890915 
epoch 4923, loss 0.05003281682729721 
epoch 4924, loss 0.05003265663981438 
epoch 4925, loss 0.05003251135349274 
epoch 4926, loss 0.05003232881426811 
epoch 4927, loss 0.05003215745091438 
epoch 4928, loss 0.050032008439302444 
epoch 4929, loss 0.05003184452652931 
epoch 4930, loss 0.05003168806433678 
epoch 4931, loss 0.05003150552511215 
epoch 4932, loss 0.05003137141466141 
epoch 4933, loss 0.05003122240304947 
epoch 4934,

epoch 5194, loss 0.04999125748872757 
epoch 5195, loss 0.04999108240008354 
epoch 5196, loss 0.0499909333884716 
epoch 5197, loss 0.04999076575040817 
epoch 5198, loss 0.04999063163995743 
epoch 5199, loss 0.04999050125479698 
epoch 5200, loss 0.04999033361673355 
epoch 5201, loss 0.04999013990163803 
epoch 5202, loss 0.04999003931879997 
epoch 5203, loss 0.049989890307188034 
epoch 5204, loss 0.04998977109789848 
epoch 5205, loss 0.04998958110809326 
epoch 5206, loss 0.04998943582177162 
epoch 5207, loss 0.04998929053544998 
epoch 5208, loss 0.04998910054564476 
epoch 5209, loss 0.04998898133635521 
epoch 5210, loss 0.049988821148872375 
epoch 5211, loss 0.04998864233493805 
epoch 5212, loss 0.0499885268509388 
epoch 5213, loss 0.049988389015197754 
epoch 5214, loss 0.049988213926553726 
epoch 5215, loss 0.04998805746436119 
epoch 5216, loss 0.04998791217803955 
epoch 5217, loss 0.049987759441137314 
epoch 5218, loss 0.049987610429525375 
epoch 5219, loss 0.04998743534088135 
epoch 52

epoch 5442, loss 0.04995590075850487 
epoch 5443, loss 0.04995576664805412 
epoch 5444, loss 0.04995563253760338 
epoch 5445, loss 0.049955498427152634 
epoch 5446, loss 0.0499553456902504 
epoch 5447, loss 0.04995520040392876 
epoch 5448, loss 0.049955058842897415 
epoch 5449, loss 0.049954917281866074 
epoch 5450, loss 0.04995477944612503 
epoch 5451, loss 0.04995463788509369 
epoch 5452, loss 0.04995451495051384 
epoch 5453, loss 0.0499543659389019 
epoch 5454, loss 0.04995419830083847 
epoch 5455, loss 0.04995403811335564 
epoch 5456, loss 0.04995393380522728 
epoch 5457, loss 0.049953803420066833 
epoch 5458, loss 0.0499536469578743 
epoch 5459, loss 0.049953531473875046 
epoch 5460, loss 0.04995336756110191 
epoch 5461, loss 0.049953240901231766 
epoch 5462, loss 0.04995312914252281 
epoch 5463, loss 0.049952950328588486 
epoch 5464, loss 0.04995278641581535 
epoch 5465, loss 0.04995268955826759 
epoch 5466, loss 0.04995250701904297 
epoch 5467, loss 0.049952346831560135 
epoch 5

epoch 5675, loss 0.049924466758966446 
epoch 5676, loss 0.049924273043870926 
epoch 5677, loss 0.04992416873574257 
epoch 5678, loss 0.04992403835058212 
epoch 5679, loss 0.049923934042453766 
epoch 5680, loss 0.049923744052648544 
epoch 5681, loss 0.04992363601922989 
epoch 5682, loss 0.04992348328232765 
epoch 5683, loss 0.04992339387536049 
epoch 5684, loss 0.049923237413167953 
epoch 5685, loss 0.049923110753297806 
epoch 5686, loss 0.049922965466976166 
epoch 5687, loss 0.04992281645536423 
epoch 5688, loss 0.049922697246074677 
epoch 5689, loss 0.04992257058620453 
epoch 5690, loss 0.04992244020104408 
epoch 5691, loss 0.04992228001356125 
epoch 5692, loss 0.04992218688130379 
epoch 5693, loss 0.04992201179265976 
epoch 5694, loss 0.04992187023162842 
epoch 5695, loss 0.04992179572582245 
epoch 5696, loss 0.04992165043950081 
epoch 5697, loss 0.04992150142788887 
epoch 5698, loss 0.049921367317438126 
epoch 5699, loss 0.04992123320698738 
epoch 5700, loss 0.04992109164595604 
epo

epoch 5924, loss 0.04989267513155937 
epoch 5925, loss 0.04989255219697952 
epoch 5926, loss 0.04989241063594818 
epoch 5927, loss 0.04989226907491684 
epoch 5928, loss 0.049892161041498184 
epoch 5929, loss 0.049892012029886246 
epoch 5930, loss 0.04989191144704819 
epoch 5931, loss 0.04989180341362953 
epoch 5932, loss 0.049891650676727295 
epoch 5933, loss 0.04989150911569595 
epoch 5934, loss 0.04989142343401909 
epoch 5935, loss 0.049891289323568344 
epoch 5936, loss 0.0498911589384079 
epoch 5937, loss 0.04989103600382805 
epoch 5938, loss 0.04989093169569969 
epoch 5939, loss 0.04989074170589447 
epoch 5940, loss 0.04989064857363701 
epoch 5941, loss 0.04989049211144447 
epoch 5942, loss 0.04989037662744522 
epoch 5943, loss 0.04989029839634895 
epoch 5944, loss 0.04989016428589821 
epoch 5945, loss 0.049890026450157166 
epoch 5946, loss 0.04988985136151314 
epoch 5947, loss 0.049889761954545975 
epoch 5948, loss 0.04988962039351463 
epoch 5949, loss 0.049889471381902695 
epoch 

epoch 6162, loss 0.049864064902067184 
epoch 6163, loss 0.049863945692777634 
epoch 6164, loss 0.04986386373639107 
epoch 6165, loss 0.049863748252391815 
epoch 6166, loss 0.049863576889038086 
epoch 6167, loss 0.04986343905329704 
epoch 6168, loss 0.04986335709691048 
epoch 6169, loss 0.04986322298645973 
epoch 6170, loss 0.04986312612891197 
epoch 6171, loss 0.049862995743751526 
epoch 6172, loss 0.049862924963235855 
epoch 6173, loss 0.04986276477575302 
epoch 6174, loss 0.04986267164349556 
epoch 6175, loss 0.04986247792840004 
epoch 6176, loss 0.049862418323755264 
epoch 6177, loss 0.04986229166388512 
epoch 6178, loss 0.04986213520169258 
epoch 6179, loss 0.04986206814646721 
epoch 6180, loss 0.04986194148659706 
epoch 6181, loss 0.04986177012324333 
epoch 6182, loss 0.04986167699098587 
epoch 6183, loss 0.049861568957567215 
epoch 6184, loss 0.04986147582530975 
epoch 6185, loss 0.04986131936311722 
epoch 6186, loss 0.04986121132969856 
epoch 6187, loss 0.049861155450344086 
epo

epoch 6445, loss 0.049831416457891464 
epoch 6446, loss 0.04983130469918251 
epoch 6447, loss 0.04983116686344147 
epoch 6448, loss 0.0498310811817646 
epoch 6449, loss 0.049830950796604156 
epoch 6450, loss 0.0498308502137661 
epoch 6451, loss 0.04983071610331535 
epoch 6452, loss 0.04983058199286461 
epoch 6453, loss 0.04983048513531685 
epoch 6454, loss 0.049830362200737 
epoch 6455, loss 0.04983028024435043 
epoch 6456, loss 0.0498301200568676 
epoch 6457, loss 0.04983002319931984 
epoch 6458, loss 0.0498298779129982 
epoch 6459, loss 0.04982980713248253 
epoch 6460, loss 0.04982973262667656 
epoch 6461, loss 0.04982957988977432 
epoch 6462, loss 0.04982944577932358 
epoch 6463, loss 0.049829352647066116 
epoch 6464, loss 0.04982922971248627 
epoch 6465, loss 0.049829110503196716 
epoch 6466, loss 0.04982899874448776 
epoch 6467, loss 0.04982887580990791 
epoch 6468, loss 0.04982879385352135 
epoch 6469, loss 0.0498286671936512 
epoch 6470, loss 0.04982855170965195 
epoch 6471, los

epoch 6714, loss 0.04980720207095146 
epoch 6715, loss 0.04981014505028725 
epoch 6716, loss 0.04981505125761032 
epoch 6717, loss 0.049822889268398285 
epoch 6718, loss 0.04983629658818245 
epoch 6719, loss 0.04985694959759712 
epoch 6720, loss 0.04989178478717804 
epoch 6721, loss 0.04994088411331177 
epoch 6722, loss 0.05001857131719589 
epoch 6723, loss 0.05010189488530159 
epoch 6724, loss 0.05020430311560631 
epoch 6725, loss 0.050226449966430664 
epoch 6726, loss 0.050188105553388596 
epoch 6727, loss 0.05002420395612717 
epoch 6728, loss 0.049867842346429825 
epoch 6729, loss 0.04980069398880005 
epoch 6730, loss 0.04984884709119797 
epoch 6731, loss 0.049944572150707245 
epoch 6732, loss 0.04998396709561348 
epoch 6733, loss 0.04994397610425949 
epoch 6734, loss 0.04985174164175987 
epoch 6735, loss 0.04980112239718437 
epoch 6736, loss 0.049823272973299026 
epoch 6737, loss 0.049875929951667786 
epoch 6738, loss 0.04989901930093765 
epoch 6739, loss 0.04986466094851494 
epoch

epoch 6990, loss 0.0497756153345108 
epoch 6991, loss 0.049775585532188416 
epoch 6992, loss 0.049774836748838425 
epoch 6993, loss 0.04977403208613396 
epoch 6994, loss 0.0497736893594265 
epoch 6995, loss 0.049773890525102615 
epoch 6996, loss 0.049774300307035446 
epoch 6997, loss 0.04977427050471306 
epoch 6998, loss 0.04977385699748993 
epoch 6999, loss 0.049773361533880234 
epoch 7000, loss 0.049773115664720535 
epoch 7001, loss 0.049773093312978745 
epoch 7002, loss 0.04977326840162277 
epoch 7003, loss 0.04977327585220337 
epoch 7004, loss 0.04977304860949516 
epoch 7005, loss 0.04977276548743248 
epoch 7006, loss 0.04977251961827278 
epoch 7007, loss 0.04977237433195114 
epoch 7008, loss 0.04977240040898323 
epoch 7009, loss 0.04977240040898323 
epoch 7010, loss 0.049772270023822784 
epoch 7011, loss 0.04977214336395264 
epoch 7012, loss 0.04977192357182503 
epoch 7013, loss 0.049771737307310104 
epoch 7014, loss 0.04977167397737503 
epoch 7015, loss 0.04977165907621384 
epoch

epoch 7274, loss 0.049746401607990265 
epoch 7275, loss 0.0497463196516037 
epoch 7276, loss 0.04974622651934624 
epoch 7277, loss 0.04974611848592758 
epoch 7278, loss 0.04974604398012161 
epoch 7279, loss 0.04974592849612236 
epoch 7280, loss 0.0497458316385746 
epoch 7281, loss 0.049745745956897736 
epoch 7282, loss 0.04974561557173729 
epoch 7283, loss 0.04974556714296341 
epoch 7284, loss 0.04974542185664177 
epoch 7285, loss 0.049745336174964905 
epoch 7286, loss 0.049745261669158936 
epoch 7287, loss 0.04974514991044998 
epoch 7288, loss 0.04974501579999924 
epoch 7289, loss 0.04974498227238655 
epoch 7290, loss 0.0497448593378067 
epoch 7291, loss 0.049744777381420135 
epoch 7292, loss 0.04974466934800148 
epoch 7293, loss 0.04974452406167984 
epoch 7294, loss 0.049744464457035065 
epoch 7295, loss 0.0497443713247776 
epoch 7296, loss 0.04974430054426193 
epoch 7297, loss 0.049744170159101486 
epoch 7298, loss 0.049744073301553726 
epoch 7299, loss 0.04974402114748955 
epoch 73

epoch 7543, loss 0.04972149431705475 
epoch 7544, loss 0.04972143843770027 
epoch 7545, loss 0.049721360206604004 
epoch 7546, loss 0.04972120746970177 
epoch 7547, loss 0.049721140414476395 
epoch 7548, loss 0.049721039831638336 
epoch 7549, loss 0.04972098767757416 
epoch 7550, loss 0.049720872193574905 
epoch 7551, loss 0.049720775336027145 
epoch 7552, loss 0.049720730632543564 
epoch 7553, loss 0.04972059652209282 
epoch 7554, loss 0.04972052574157715 
epoch 7555, loss 0.04972038418054581 
epoch 7556, loss 0.04972029849886894 
epoch 7557, loss 0.04972025007009506 
epoch 7558, loss 0.04972014203667641 
epoch 7559, loss 0.04972004145383835 
epoch 7560, loss 0.0497199222445488 
epoch 7561, loss 0.049719829112291336 
epoch 7562, loss 0.04971974343061447 
epoch 7563, loss 0.0497196763753891 
epoch 7564, loss 0.049719568341970444 
epoch 7565, loss 0.04971949756145477 
epoch 7566, loss 0.049719396978616714 
epoch 7567, loss 0.04971931129693985 
epoch 7568, loss 0.0497191920876503 
epoch 

epoch 7822, loss 0.04969703406095505 
epoch 7823, loss 0.04969692975282669 
epoch 7824, loss 0.04969683662056923 
epoch 7825, loss 0.04969676584005356 
epoch 7826, loss 0.049696724861860275 
epoch 7827, loss 0.049696605652570724 
epoch 7828, loss 0.049696456640958786 
epoch 7829, loss 0.049696359783411026 
epoch 7830, loss 0.04969632253050804 
epoch 7831, loss 0.04969623312354088 
epoch 7832, loss 0.04969612881541252 
epoch 7833, loss 0.04969603940844536 
epoch 7834, loss 0.04969596117734909 
epoch 7835, loss 0.04969586804509163 
epoch 7836, loss 0.049695782363414764 
epoch 7837, loss 0.0496956966817379 
epoch 7838, loss 0.04969565197825432 
epoch 7839, loss 0.049695536494255066 
epoch 7840, loss 0.049695443361997604 
epoch 7841, loss 0.049695324152708054 
epoch 7842, loss 0.049695245921611786 
epoch 7843, loss 0.049695149064064026 
epoch 7844, loss 0.04969510808587074 
epoch 7845, loss 0.049694959074258804 
epoch 7846, loss 0.04969491809606552 
epoch 7847, loss 0.04969482496380806 
ep

epoch 8102, loss 0.04967386648058891 
epoch 8103, loss 0.04967376962304115 
epoch 8104, loss 0.049673695117235184 
epoch 8105, loss 0.049673572182655334 
epoch 8106, loss 0.04967354238033295 
epoch 8107, loss 0.049673404544591904 
epoch 8108, loss 0.04967329278588295 
epoch 8109, loss 0.04967324435710907 
epoch 8110, loss 0.049673184752464294 
epoch 8111, loss 0.04967311769723892 
epoch 8112, loss 0.04967302456498146 
epoch 8113, loss 0.049672968685626984 
epoch 8114, loss 0.04967286065220833 
epoch 8115, loss 0.04967276751995087 
epoch 8116, loss 0.049672696739435196 
epoch 8117, loss 0.049672648310661316 
epoch 8118, loss 0.04967263713479042 
epoch 8119, loss 0.049672581255435944 
epoch 8120, loss 0.049672577530145645 
epoch 8121, loss 0.0496726892888546 
epoch 8122, loss 0.049672845751047134 
epoch 8123, loss 0.049673113971948624 
epoch 8124, loss 0.049673642963171005 
epoch 8125, loss 0.049674589186906815 
epoch 8126, loss 0.049676116555929184 
epoch 8127, loss 0.04967883601784706 

epoch 8372, loss 0.04990382865071297 
epoch 8373, loss 0.049829982221126556 
epoch 8374, loss 0.049699343740940094 
epoch 8375, loss 0.049653470516204834 
epoch 8376, loss 0.049711648374795914 
epoch 8377, loss 0.0497802272439003 
epoch 8378, loss 0.049780018627643585 
epoch 8379, loss 0.04970761388540268 
epoch 8380, loss 0.04965485259890556 
epoch 8381, loss 0.049669113010168076 
epoch 8382, loss 0.04971490427851677 
epoch 8383, loss 0.049730680882930756 
epoch 8384, loss 0.04969559237360954 
epoch 8385, loss 0.04965776950120926 
epoch 8386, loss 0.049656495451927185 
epoch 8387, loss 0.04968271777033806 
epoch 8388, loss 0.049698106944561005 
epoch 8389, loss 0.04968244954943657 
epoch 8390, loss 0.04965827986598015 
epoch 8391, loss 0.0496523380279541 
epoch 8392, loss 0.049666110426187515 
epoch 8393, loss 0.04967798292636871 
epoch 8394, loss 0.04967217892408371 
epoch 8395, loss 0.04965772107243538 
epoch 8396, loss 0.04965110495686531 
epoch 8397, loss 0.04965728893876076 
epoc

epoch 8654, loss 0.049633778631687164 
epoch 8655, loss 0.04963260143995285 
epoch 8656, loss 0.04963185265660286 
epoch 8657, loss 0.0496320016682148 
epoch 8658, loss 0.04963258281350136 
epoch 8659, loss 0.04963286221027374 
epoch 8660, loss 0.049632478505373 
epoch 8661, loss 0.049631837755441666 
epoch 8662, loss 0.04963141679763794 
epoch 8663, loss 0.04963146150112152 
epoch 8664, loss 0.04963172599673271 
epoch 8665, loss 0.04963186755776405 
epoch 8666, loss 0.04963163658976555 
epoch 8667, loss 0.04963129758834839 
epoch 8668, loss 0.049631036818027496 
epoch 8669, loss 0.049630921334028244 
epoch 8670, loss 0.04963099956512451 
epoch 8671, loss 0.04963109269738197 
epoch 8672, loss 0.04963104426860809 
epoch 8673, loss 0.04963080212473869 
epoch 8674, loss 0.04963055998086929 
epoch 8675, loss 0.049630437046289444 
epoch 8676, loss 0.04963044822216034 
epoch 8677, loss 0.04963049665093422 
epoch 8678, loss 0.04963041841983795 
epoch 8679, loss 0.049630336463451385 
epoch 868

epoch 8918, loss 0.049613580107688904 
epoch 8919, loss 0.04961349442601204 
epoch 8920, loss 0.04961341619491577 
epoch 8921, loss 0.0496133416891098 
epoch 8922, loss 0.04961329326033592 
epoch 8923, loss 0.04961325600743294 
epoch 8924, loss 0.049613144248723984 
epoch 8925, loss 0.04961312934756279 
epoch 8926, loss 0.049612972885370255 
epoch 8927, loss 0.049612920731306076 
epoch 8928, loss 0.04961287975311279 
epoch 8929, loss 0.04961279407143593 
epoch 8930, loss 0.04961271211504936 
epoch 8931, loss 0.04961264505982399 
epoch 8932, loss 0.049612581729888916 
epoch 8933, loss 0.04961255565285683 
epoch 8934, loss 0.04961245134472847 
epoch 8935, loss 0.049612391740083694 
epoch 8936, loss 0.049612320959568024 
epoch 8937, loss 0.049612320959568024 
epoch 8938, loss 0.04961217939853668 
epoch 8939, loss 0.0496121309697628 
epoch 8940, loss 0.04961203411221504 
epoch 8941, loss 0.04961202293634415 
epoch 8942, loss 0.04961191490292549 
epoch 8943, loss 0.04961179569363594 
epoch 

epoch 9202, loss 0.049594733864068985 
epoch 9203, loss 0.04959471896290779 
epoch 9204, loss 0.04959462583065033 
epoch 9205, loss 0.049594536423683167 
epoch 9206, loss 0.0495944619178772 
epoch 9207, loss 0.049594443291425705 
epoch 9208, loss 0.049594391137361526 
epoch 9209, loss 0.04959429055452347 
epoch 9210, loss 0.04959424212574959 
epoch 9211, loss 0.04959414526820183 
epoch 9212, loss 0.049594078212976456 
epoch 9213, loss 0.04959401860833168 
epoch 9214, loss 0.0495939627289772 
epoch 9215, loss 0.04959389194846153 
epoch 9216, loss 0.04959383234381676 
epoch 9217, loss 0.04959378391504288 
epoch 9218, loss 0.0495937205851078 
epoch 9219, loss 0.04959358274936676 
epoch 9220, loss 0.04959359019994736 
epoch 9221, loss 0.04959351196885109 
epoch 9222, loss 0.04959343001246452 
epoch 9223, loss 0.04959337040781975 
epoch 9224, loss 0.04959331080317497 
epoch 9225, loss 0.049593254923820496 
epoch 9226, loss 0.04959319904446602 
epoch 9227, loss 0.049593109637498856 
epoch 92

epoch 9482, loss 0.0495775006711483 
epoch 9483, loss 0.04957740381360054 
epoch 9484, loss 0.04957734793424606 
epoch 9485, loss 0.049577318131923676 
epoch 9486, loss 0.049577224999666214 
epoch 9487, loss 0.04957716539502144 
epoch 9488, loss 0.04957710579037666 
epoch 9489, loss 0.04957706853747368 
epoch 9490, loss 0.04957698658108711 
epoch 9491, loss 0.049576934427022934 
epoch 9492, loss 0.04957681521773338 
epoch 9493, loss 0.0495767742395401 
epoch 9494, loss 0.049576710909605026 
epoch 9495, loss 0.04957667738199234 
epoch 9496, loss 0.04957660660147667 
epoch 9497, loss 0.0495765283703804 
epoch 9498, loss 0.04957647621631622 
epoch 9499, loss 0.04957641288638115 
epoch 9500, loss 0.04957633092999458 
epoch 9501, loss 0.0495762899518013 
epoch 9502, loss 0.04957622289657593 
epoch 9503, loss 0.04957618564367294 
epoch 9504, loss 0.04957609623670578 
epoch 9505, loss 0.049576062709093094 
epoch 9506, loss 0.049575984477996826 
epoch 9507, loss 0.049575913697481155 
epoch 950

epoch 9751, loss 0.049561962485313416 
epoch 9752, loss 0.04956187307834625 
epoch 9753, loss 0.049561865627765656 
epoch 9754, loss 0.04956177622079849 
epoch 9755, loss 0.04956173524260521 
epoch 9756, loss 0.049561675637960434 
epoch 9757, loss 0.049561645835638046 
epoch 9758, loss 0.049561575055122375 
epoch 9759, loss 0.049561526626348495 
epoch 9760, loss 0.049561433494091034 
epoch 9761, loss 0.049561403691768646 
epoch 9762, loss 0.04956141486763954 
epoch 9763, loss 0.04956137016415596 
epoch 9764, loss 0.04956137761473656 
epoch 9765, loss 0.04956144094467163 
epoch 9766, loss 0.04956155642867088 
epoch 9767, loss 0.04956173151731491 
epoch 9768, loss 0.04956215247511864 
epoch 9769, loss 0.04956294968724251 
epoch 9770, loss 0.049564290791749954 
epoch 9771, loss 0.04956657811999321 
epoch 9772, loss 0.04957051947712898 
epoch 9773, loss 0.04957748204469681 
epoch 9774, loss 0.049589116126298904 
epoch 9775, loss 0.049610018730163574 
epoch 9776, loss 0.04964377358555794 
e

In [15]:
def greates_3(x):
    if x[0]> x[1]:
        if(x[0]>x[2]):
            return x[0]
        else:
            return x[2]
    elif(x[1]>x[2]):
        return x[1]
    else:
        return x[2]
greates_3([2,3,1])

3

In [16]:
pred_y=model.predict(test_x)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:26: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


In [17]:
pred_y

tensor([2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 0, 0, 2, 2, 2, 2, 0, 1, 1, 1, 0, 1, 0, 1,
        0, 1, 2, 2, 0, 1])

# testing error

In [18]:
# Python script for confusion matrix creation. 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

results = confusion_matrix(test_y, pred_y) 
  
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(test_y, pred_y)) 
print('Report : ')
print(classification_report(test_y, pred_y)) 

Confusion Matrix :
[[ 7  0  0]
 [ 0 14  0]
 [ 0  0  9]]
Accuracy Score : 1.0
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         9

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# training error

In [19]:
results = confusion_matrix(train_y, model.predict(train_x)) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(train_y, model.predict(train_x))) 
print('Report : ')
print(classification_report(train_y,model.predict(train_x))) 

Confusion Matrix :
[[43  0  0]
 [ 0 35  1]
 [ 0  1 40]]
Accuracy Score : 0.9833333333333333
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        43
           1       0.97      0.97      0.97        36
           2       0.98      0.98      0.98        41

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120



/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:26: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
