#### various random variable used
- weights
- bias

note  :-  in order to multiply matrix ,then number of columns in first matrix must be equal to number rows in the second matris

note :- Dimension property
The product of an \blueD m\times \maroonC nm×nstart color #11accd, m, end color #11accd, times, start color #ed5fa6, n, end color #ed5fa6 matrix and an \maroonC n\times \goldD kn×kstart color #ed5fa6, n, end color #ed5fa6, times, start color #e07d10, k, end color #e07d10 matrix is an \blueD m\times \goldD km×kstart color #11accd, m, end color #11accd, times, start color #e07d10, k, end color #e07d10 matrix.

m*n mult j*k then n and j should be equal.



y = x1w1+x2w2+x3w3 + bias

In [1]:
import numpy as np

In [ ]:
def matrix_mult(mat1,mat2):
    #checking the validaity of the dote product
    if(mat1.shape[1] != mat2.shape[0]):
        print("sorry invalied shapes to multiply")
        break
    else:
        resultent_shape = (mat1.shape[0],mat2.shape[1])
        resultent_matrix = []
        
    
    
    
    

In [ ]:
class Neural_network_model:
    def linear(self,num_input,num_output,bias = True):
        self.num_input = num_input
        self.num_output = num_output
        self.bias = bias
        
        
        
        

In [17]:
def fun(arg):
    for i in arg:
        print("elements")
        print(i)
fun(np.array([[1,2,3],[4,5,6],[7,8,9]]))

elements
[1 2 3]
elements
[4 5 6]
elements
[7 8 9]


In [21]:
w1 = np.array([1,2,3,5])
w2 = np.array([4,5,6,7])
bias = np.array([1,2,3,4])

In [22]:
w1*x1

array([ 1,  4,  9, 20])

In [25]:
len(w1)

4

In [34]:
ar=np.array([[1,2],[3,4],[5,6],[8,9]])
ar

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 9]])

In [57]:
ar1 = np.array([[1,2,3],[4,5,6]])
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
np.dot(ar1,w)+np.array([[56],[68]])

array([[ 471],
       [1053]])

In [75]:
w = np.array([[45],[65],[80]])
w.shape

(3, 1)

In [70]:
arr = []
for i in range(0,ar.shape[0]):
    for j in range(0,ar.shape[1]):
        print("first array elements")
        print(ar[i][j])
        print("second array")
        print(ar1[:,i][j])
        

first array elements
1
second array
1
first array elements
2
second array
4
first array elements
3
second array
2
first array elements
4
second array
5
first array elements
5
second array
3
first array elements
6
second array
6
first array elements
8
second array


IndexError: index 3 is out of bounds for axis 1 with size 3

In [53]:
ar[0][0]

1

In [61]:
ar

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 9]])

In [62]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
ar1[:,0][0]

1