# Tensorflow class

#### Difference between 1.0 and 2.0

Earlier this year, Google announced TensorFlow 2.0, it is a major leap from the existing TensorFlow 1.0. The key differences are as follows:

 

Ease of use: Many old libraries (example tf.contrib) were removed, and some consolidated. For example, in TensorFlow1.x the model could be made using Contrib, layers, Keras or estimators, so many options for the same task confused many new users. TensorFlow 2.0 promotes TensorFlow Keras for model experimentation and Estimators for scaled serving, and the two APIs are very convenient to use.

 

Eager Execution:  In TensorFlow 1.x. The writing of code was divided into two parts: building the computational graph and later creating a session to execute it. this was quite cumbersome, especially if in the big model that you have designed, a small error existed somewhere in the beginning. TensorFlow2.0 Eager Execution is implemented by default, i.e. you no longer need to create a session to run the computational graph,  you can see the result of your code directly without the need of creating Session.

Model Building and deploying made easy:  With TensorFlow2.0 providing high level TensorFlow Keras API, the user has a greater flexibility in creating the model. One can define model using Keras functional or sequential API. The TensorFlow Estimator API allows one to run model on a local host or on a distributed multi-server environment without changing your model. Computational graphs are powerful in terms of performance, in TensorFlow 2.0 you can use the decorator tf.function so that the following function block is run as a single graph. This is done via the powerful Autograph feature of TensorFlow 2.0. This allows users to optimize the function and increase portability. And the best part you can write the function using natural Python syntax. Effectively, you can use the decorator tf.function to turn  plain Python code into graph. While the decorator @tf.function applies to the function block immediately following it, any functions called by it will be executed in graph mode as well. Thus, in TensorFlow 2.0, users should refactor their code into smaller functions which are called as needed. In general, it's not necessary to decorate each of these smaller functions with tf.function; only use tf.function to decorate high-level computations - for example, one step of training, or the forward pass of your model. (source stack overflow and TF2 documentation)

To expand this idea, In TensorFlow 1.x we needed to build the computational graph. TensorFlow 2.0 does not build graph by default. However, as every Machine Learning engineer knows, graphs are good for speed. TensorFlow 2.0 provides the user to create a callable graph using a python function @tf.function. The tf.function() will create a separate graph for every unique set of input shapes and datatypes. In the example below we will have three separate graphs created, one for each input datatype.

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.15.0


#### Building a computational graph

In [3]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://www.oreilly.com/library/view/learning-tensorflow/9781491978504/assets/letf_0105.png",width=500, height=500)

In tensorflow 2.0 there is no need of building and running computatuinal graph seperatly

In [3]:
node_1 = tf.constant(2.9)
node_2 = tf.constant(3.1)
node_3 = node_1+node_2
#tf.print("The sum of node1 and node2 is :-",node_3,"",tf.constant("hello"))
node_3

<tf.Tensor 'add:0' shape=() dtype=float32>

## tensorflow 1.15 version code

In [4]:
#creating a computational graph.
node_1 = tf.constant(2.4)
node_2 = tf.constant(34.3)
node_3 = node_1 + node_2
print(node_3)
se = tf.Session()
se.run(node_3)

Tensor("add_1:0", shape=(), dtype=float32)


36.7

There are three types of data in tensorflow

- constant
- place holder 
- variable

# Constants

In tensorflow every thing is present in form of sessions,so firt we need to run the session,and its always good to close after using the session.

In [5]:
#working version
hello = tf.constant("rohan")
print(hello)

Tensor("Const_4:0", shape=(), dtype=string)


In [8]:
#first argument is value and the second argument is type casting
x=tf.constant(32,tf.float32)
y=tf.constant(45,tf.float32)
node = x+y

creating a session

In [9]:
sess=tf.Session()
sess.run(node)

77.0

# place holder data 

we are going to use frequently this type of data type

A place holder is a promise to provide a value later

In [12]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
node = x+y
sess = tf.Session()
sess.run(node,{x:[1,2],y:[4,5]})

numpy.ndarray

In [26]:
a=tf.compat.v1.placeholder(tf.float64)
b=tf.compat.v1.placeholder(tf.float64)
node_add=a+b
sess=tf.compat.v1.Session()
sess.run(node_add,feed_dict={a:[1,2,3],b:[5,6,7]})
sess.close()

In [18]:
node_mult=a*b
sess = tf.Session()
sess.run(node_mult,feed_dict={a:[5,6,7],b:[10,11,12]})

array([50., 66., 84.])

In [29]:
tf.compat.v2.TensorArray

tensorflow.python.ops.tensor_array_ops.TensorArray

In [30]:
x=[1,2,3,4]
len(x)/2

2.0

In [25]:
'''
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
node = x*y
tf.Session(node,{x:[1.,2.,3.],y:[5.,6.,8.]})
'''
x=tf.placeholder(tf.float32)
y=tf.placeholder(tf.float32)
node = x*y
sess = tf.Session()
sess.run(node,feed_dict = {a:[5,6,7],b:[10,11,12]})

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_12' with dtype float
	 [[node Placeholder_12 (defined at /usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'Placeholder_12':
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/local/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 563, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 538, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1782, in _run_once
    handle._run()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/usr/local/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 787, in inner
    self.run()
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2855, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-427be2f842ab>", line 8, in <module>
    y=tf.placeholder(tf.float32)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2619, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6669, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


 # Tensorflow variable

variables allow us to have variable parameters of the graph.

The below code is the new version 2.0 code.

In [27]:
node = a*b
tf.Variable([1,2,3],tf.float32),tf.Variable([5,6,7],tf.float32)

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32_ref>,
 <tf.Variable 'Variable_1:0' shape=(3,) dtype=int32_ref>)

In [28]:
w1=tf.Variable([.5],tf.float64)
init=tf.compat.v1.global_variables_initializer()
sess=tf.compat.v1.Session()
sess.run(init)
sess.run(tf.print(w1))

[0.5]


In [29]:
sess=tf.compat.v1.Session()
sess.run(tf.print(tf.multiply(2,3)))
sess.run(tf.add(4,5))
sess.close()

6


# How to change the data type of the variable

Note :-  tf.matmul is the function by which we can perform matrix multiplaction,tf.cast is the function by which we can type cast the variable of the tensorflow

In [ ]:
sess.run(tf.print(tf.compat.v1.subtract(tf.constant(23),tf.cast(23,tf.int32))))

In [ ]:
sess.run(tf.print(tf.constant(23)/tf.constant(23)))

# Activation function

Activation function translates the inputs into outputs.It uses a threshold to produce an output.some useful activation are :- 

- Linear or Identity
- unit or Binary Step
- Sigmoid or Logistic
- Tanh
- ReLu
- Softmax

## Linear or Identity function

- A Linear transform is basically the identity function ,where the dependent variable has a direct,proportional relationship with the independent variable

- In practical terms,it means the function passes the signal through unchange

- f(x)=x

##### Where it is being used in neural network?

when we want to solve a Linear Regression problem ,we apply Linear transformation function

## Unit step function

- The output of the unit step function is either 1 or 0
- It depends on the threshold value we define.

##### Where it is used in neural network?

- when we want to solve binary classification problem ,we use unit step function

## Sigmoid or Logistic Activation function

- Its called the hero of activation function 
- A sigmoid function is a machine that converts independent variable of near infinite range into simple probability between 0 and 1
- Most of its output will be very close to 0 and 1
- If you give any value between -infinity to +infinity ,the it can convert its range to 0 and 1
- If the input is positive ,the out will be nearly close to 1,if the input is negative ,then the output will be closer to zero

## Tanh function

- Tanh is a hyperbolic trigonometric function.
- Unlike the sigmoid function,the normalized range of Tanh is -1 to 1.The advantage of tanH is that it can deal more easily with negative numbers.
- This function is used to extract best values of weight.where as the sigmoid is used in output layer of neural networks.
- If we pass 0 to sigmoid function ,then the output would be 0.5,but if we pass 0 to TanH function ,then the output would be 0

## Rectified Linear Unit(ReLu)

when we want to map input values to a value in the range(input x to max(0,x)),it maps negative inputs to 0 and positive input are output with out any change .

- f(x)= 0 if x<0
- f(x)= x if x>=0

Note :- This is the algorithm being used by for deriving most the intellegent weight in the neural networks

## Softmax function

- when we have four or five classes of outputs,the softmax function will give the probability distribution of each
- It is useful for finding out the class which has the maximum probability 
- Softmax is the function you will often find at the output layers of a clasifiers

Note :- The softmax can also be used in binary classification ,but it is mostly used in multi class classification

# Neural Networks

Deep Learning is a form of machine learning that uses a model of computing that 's very much inspired by the structure of the brain,

- The first neural network is "perceptron"

## Algorithm of perceptron

# perceptron

- Inititialize the weights and threshold
- provide the input and calculate the output
- update the weights
- repeat step 2 and 3

In [53]:
b = tf.Variable([.3],tf.float32)

In [54]:
w = tf.Variable([.5],tf.float32)

In [56]:
x = tf.placeholder(tf.float32)

In [55]:
linear_model = x+

TypeError: Expected float32, got <re.Match object; span=(3, 4), match=' '> of type 'Match' instead.

In [16]:
import regex
s = regex.search(r"(\b" + "NO 122.124. JALAN DEDAP 13 81100 JOHOR BAHRU" + r"\b){e<=" + "fgfdf" + r"}", "heloo how do you do")

error: bad fuzzy cost limit at position 54

In [17]:
import re

txt = "The rain in Spain"
x = re.search("\s", txt)

In [35]:
x.span()

(3, 4)

In [49]:
x[0]

' '

In [52]:
x[2]

IndexError: no such group

In [46]:
e = 0
while(e<3):
    s=re.search(r"(\b" + v + r"\b){e<=" + str(e) + r"}",st)
    print(s)
    e+=1

None
None
None


In [41]:
st="NO.50 , JALAN PBS 14/11 , KAWASAN PERINDUSTRIAN BUKIT SERDANG, TEL : 03-89410243 FAX : 03-89410243 GST REG NO. : 000549584896 TAX INVOICE INVOICE NO. : CR 1803/0064 DATE : 01-03-18 5:23:26 PM CASHIER NO. : KHOO COUNTER NO. : C1 PRINTED DATE : 01-03-18 5:23:30 PM ITEM NAME QTY UNIT PRICE AMOUNT AIR ADAPTOR @ 1 5 4.00 20.00 SR 5 ITEM(S) TOTAL (MYR) : 20.00 GST @ 6% : 1.20 NET TOTAL (MYR) : 21.20 ROUNDING ADJ. : 0.00 NET TOTAL ROUNDED (MYR) : 21.20 CASH : 21.20 CHANGE : 0.00 GST SUMMARY ITEM AMOUNT (MYR) GST (MYR) SR @ 6% 1 20.00 1.20 THANK YOU. PLEASE COME AGAIN !"

In [47]:
st="NO.50,JALAN PBS 14/11 , KAWASAN PERINDUSTRIAN BUKIT SERDANG,"

In [48]:
v="NO.50,JALAN PBS 14/11, KAWASAN PERINDUSTRIAN BUKIT SERDANG,"

## Tensorflow bootcamp

In [1]:
import tensorflow as tf

In [2]:
print(tf.version.VERSION)

2.2.0


### creating tensors

In [3]:
#scalar values
string = tf.Variable("hello",tf.string)
float_values = tf.Variable(2.3,tf.float16)
int_values = tf.Variable(3,tf.float16)

In [4]:
print(int_values)
print(float_values)
print(int_values)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.3>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>


we can not print the values outside the session ,the above output just displaying the objects

## rank - degree of the tensor

In [14]:
var1 = tf.Variable([1,2,3],tf.float16) #its a vector
var2 = tf.Variable([[[1,2,3],[4,5,6]],[[10,11,12],[50,60,70]]],tf.float16)

In [15]:
#Its showing the dimensions of the tensor ,whether its one dimension or 2 98l;dimension.,the rank does that.
tf.rank(var2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

## changing the shape

In [22]:
ones_tensors=tf.ones([1,2,3])
ones_tensors2 = tf.reshape(ones_tensors,[2,3,1])
ones_tensors3 = tf.reshape(ones_tensors,[3,-1])

In [23]:
print(ones_tensors)
print("-------------")
print(ones_tensors2)
print("-------------")
print(ones_tensors3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
-------------
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
-------------
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## types of variables

 - placeholder
 - constants
 - variables
 - sparseTensors