from [here](https://www.analyticsvidhya.com/blog/2019/09/introduction-to-pytorch-from-scratch/) and form [here](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

Pytorch tensors are multidimensinal arrays.
- FloatTensor: 32-bit float
- DoubleTensor: 64-bit float
- HalfTensor: 16-bit float
- IntTensor: 32-bit int
- LongTensor: 64-bit int

In [1]:
import torch
#import numpy as np

In [2]:
#initialize an array
a = torch.tensor(1)
print(a)

tensor(1)


In [3]:
#check type
type(a)

torch.Tensor

#### Math operations

In [4]:
#intialize tensor
a = torch.tensor(2)
b = torch.tensor(5)
print(a,b)

tensor(2) tensor(5)


In [5]:
#addition
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor(7)
tensor(-3)
tensor(10)
tensor(0)


#### 3. Matrix intialization

In [6]:
#matrix
a = torch.zeros((3,3))
print(a)
print(a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [7]:
a = torch.ones((3,3))
print(a)
print(a.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3, 3])


In [8]:
torch.manual_seed(42)
a = torch.randn(3,3)
a

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

In [9]:
#zero matrix with "Long" dtype
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
#construct a tensor directly from data
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

#### 4,. Matrix operations

In [11]:
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)

In [12]:
#matrix addition
print(torch.add(a,b),'\n')

#matrix subtraction
print(torch.sub(a,b),'\n')

#matrix multiplication
print(torch.mm(a,b), '\n')

#matrix division
print(torch.div(a,b))

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]]) 

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]]) 

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]]) 

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


**.mm() is similar to dot product in numpy**

In [13]:
#matrix transpose
torch.t(a)

tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])

In [14]:
#matrix concating vertically
torch.cat((a,b))

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]])

In [15]:
#matrix concating horizontally
torch.cat((a,b), dim = 1)

tensor([[ 0.3367,  0.1288,  0.2345,  0.2674,  0.5349,  0.8094],
        [ 0.2303, -1.1229, -0.1863,  1.1103, -1.6898, -0.9890],
        [ 2.2082, -0.6380,  0.4617,  0.9580,  1.3221,  0.8172]])

#### 4. reshape tensors

In [16]:
#reshape
c = a.reshape(1,9)
print(c)
c.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380,
          0.4617]])


torch.Size([1, 9])

#### 5. Numpy Array to pytorch Tensor

In [17]:
import numpy as np

a = np.array([[1,2],[3,4]])
print(a,'\n')

#convert numpy to tensor
tensor = torch.from_numpy(a)
print(tensor)

[[1 2]
 [3 4]] 

tensor([[1, 2],
        [3, 4]])


### 6. Common pytorch modules

#### 6.1. Autograd Module
- Pytorch has Autograd Module that records all the operations that we perform and replays backward to compute gradients.
- This helps us to save time on each epoch to calculate gradient on the forward pass itself.

In [18]:
a =torch.ones((2,2), requires_grad = True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

`requires_grad = True` makes sure that gradients are stored, when ever we make some operations on it.

In [19]:
b = a+5
c = b.mean()
print(b,c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor(6., grad_fn=<MeanBackward0>)


we first added `5` to all the elements of a tensor, and then taken `mean` of it.

$b = a+5$

$c= mean(b) = summation(a+5)/4$

now the derivative of `C` w.r.t `a` will be 1/4 and hence the `Gradient matrix` will be 0.25

In [20]:
#backpropogate
c.backward()

#computing grad
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


> The autograd module helps us to compute the gradients in the forward pass itself which saves a lot of computation time of an epoch.

#### 6.2 Optim Module

it has optimizers that are used while building Neural Networks.
- SGD
- Adam
- Adadelta
- Adagrad
- AdamW
- SparseAdam
- Adamax
- ASGD (Averaged Stochastic Gradient Descent)
- RMSprop
- Rprop (resilient backpropagation)

In [21]:
#import optim module
from torch import optim

#adam
#adam = optim.Adam(model.parameters(), lr= learning_rate)

# sgd
## SGD = optim.SGD(model.parameters(), lr=learning_rate)

In [26]:
tensor = torch.tensor([[1,2,3],[3,4,5]])

In [34]:
tnesor = tensor.view((1,6))

In [35]:
tnesor

tensor([[1, 2, 3, 3, 4, 5]])