In [49]:
torch.cuda.is_available()

False

In [29]:
import torch

In [30]:
a=torch.tensor(8)
b=torch.tensor(10)
print(a)
print(b)

tensor(8)
tensor(10)


In [31]:
a = torch.tensor(8.0,requires_grad=True)
b = torch.tensor(9.0,requires_grad = True)

In [32]:
c = a*2
print(c)

tensor(16., grad_fn=<MulBackward0>)


In [38]:
x=torch.tensor([1.,2.,3.,4.],requires_grad = True)

In [40]:
y=x+2

In [42]:
y

tensor([3., 4., 5., 6.], grad_fn=<AddBackward0>)

In [43]:
out=y.mean()

In [44]:
out

tensor(4.5000, grad_fn=<MeanBackward0>)

In [45]:
out.backward()

In [48]:
x.grad

tensor([0.2500, 0.2500, 0.2500, 0.2500])

In [15]:
c.backward()

In [16]:
c

tensor(16., grad_fn=<MulBackward0>)

In [17]:
print(a)
print(b)

tensor(8., requires_grad=True)
tensor(9., requires_grad=True)


In [26]:
a = torch.ones((8,2),requires_grad=True)
b = torch.ones((4,3),requires_grad = True)

In [27]:
c = a*2
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]], grad_fn=<MulBackward0>)


In [28]:
c.backward()
print(a)

RuntimeError: grad can be implicitly created only for scalar outputs

In [ ]:
RuntimeError: grad can be implicitly created only for scalar outputs
RuntimeError: grad can be implicitly created only for scalar outputs
RuntimeError: grad can be implicitly created only for scalar outputs
