### All Packages and Description
- torch -> Main Tensor Library
- torch.nn ->  A Subpackage that contains modules and extensible classes for building neural network.
- torch.autograd -> A subpackage that supports all **differentiable tensor operation** in pytorch.
- torch.nn.functional ->it has **Loss Functions, Activation functions, and Convolution operation**.
- torch.optim -> contains SGD, ADAM and More.
- torch.utils -> contains utility clasess to load **datasets,dataloaders**.
- torchvision -> for **datasets, model architecture** and more.
- torchvision.transforms -> to transform/preprocess your data

- **index**(0), in **Computer science** its *Number*, in **Mathematics** its *Scalar*.
- **index**(1), in **Computer science** its *Array*, in **Mathematics** its *Vector*.
- **index**(2), in **Computer science** its *2d-array*, in **Mathematics** its *matrix*.
- **index**(n, in **Computer science** its *nd-array*, in **Mathematics** its *nd-tensor*.

### moving code to GPU


In [2]:
import torch

In [3]:
device = torch.device('cuda:0')

In [4]:
device

device(type='cuda', index=0)

here index 0 is saying move all your code to first gpu. If you say 'cuda:3', then you should have 4 gpus with you.

### Note

#### case-1

In [5]:
import torch
t1 = torch.tensor([1,2,3])
t1

tensor([1, 2, 3])

In [6]:
t2 = torch.tensor([1.,2.,3.])
t2

tensor([1., 2., 3.])

In [7]:
#adding t1,t2 throws Error
t1+t2

tensor([2., 4., 6.])

#### Case-2

In [8]:
#note the diff here
import numpy as np
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [9]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [10]:
torch.tensor(data)

tensor([1, 2, 3])

in both the above cells Notice that, **Tensor** returned **floats**, while **tensor** returned **ints**

### few oprations

In [11]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [12]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [13]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [14]:
torch.rand(2,2)

tensor([[0.7758, 0.0136],
        [0.9725, 0.8905]])

### Notice 1

In [68]:
t = torch.tensor([[1,1,1,1],
                [2,2,2,2],
                [3,3,3,3]], dtype = torch.float32)

In [69]:
t.shape

torch.Size([3, 4])

In [70]:
t.size()

torch.Size([3, 4])

In [71]:
#to know number of elements
t.numel()

12

In [72]:
#reshape
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [73]:
#reshape
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [74]:
#reshape
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

### Squeeze and Unsqueeze

In [75]:
#original
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [76]:
#squeezed or flatten to rank1 tensor which mean only 1 axis
print(t.reshape(1,12).squeeze())
print(t.reshape(1,-1).squeeze().shape)
#look here, we replace 12 with -1, which means automatically 
#calculates the size of t.

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [77]:
#unsqueezed
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


### Concat

In [81]:
t1 = torch.tensor([[1,2],
                  [3,4]])
t1

tensor([[1, 2],
        [3, 4]])

In [83]:
t2 = torch.tensor([[5,6],
                  [7,8]])
t2

tensor([[5, 6],
        [7, 8]])

In [84]:
#concat row wise
torch.cat((t1,t2),dim =0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [85]:
#concat column wise
torch.cat((t1,t2),dim = 1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

### CNN Flatten visualized

In [90]:
t1 = torch.rand(4,4)

In [92]:
t2  = torch.rand(4,4)

In [93]:
t3 = torch.rand(4,4)

In [100]:
#now stack them up
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [101]:
t

tensor([[[0.9869, 0.7053, 0.9614, 0.5747],
         [0.4070, 0.6991, 0.1532, 0.9386],
         [0.4735, 0.7032, 0.3851, 0.7180],
         [0.2052, 0.3957, 0.5808, 0.1698]],

        [[0.8906, 0.0961, 0.1576, 0.6826],
         [0.1933, 0.8078, 0.6731, 0.6201],
         [0.1704, 0.7303, 0.4715, 0.4375],
         [0.7565, 0.5594, 0.1796, 0.2615]],

        [[0.1866, 0.6286, 0.4785, 0.9504],
         [0.1650, 0.6815, 0.6451, 0.0425],
         [0.3692, 0.0742, 0.7326, 0.7904],
         [0.2136, 0.1404, 0.9761, 0.9162]]])

As CNN's also consider Color channel in its inputs, lets add color channel

In [102]:
t = t.reshape(3,1,4,4)

In [103]:
t

tensor([[[[0.9869, 0.7053, 0.9614, 0.5747],
          [0.4070, 0.6991, 0.1532, 0.9386],
          [0.4735, 0.7032, 0.3851, 0.7180],
          [0.2052, 0.3957, 0.5808, 0.1698]]],


        [[[0.8906, 0.0961, 0.1576, 0.6826],
          [0.1933, 0.8078, 0.6731, 0.6201],
          [0.1704, 0.7303, 0.4715, 0.4375],
          [0.7565, 0.5594, 0.1796, 0.2615]]],


        [[[0.1866, 0.6286, 0.4785, 0.9504],
          [0.1650, 0.6815, 0.6451, 0.0425],
          [0.3692, 0.0742, 0.7326, 0.7904],
          [0.2136, 0.1404, 0.9761, 0.9162]]]])

In [104]:
#Now flatten
t.reshape(1,-1)

tensor([[0.9869, 0.7053, 0.9614, 0.5747, 0.4070, 0.6991, 0.1532, 0.9386, 0.4735,
         0.7032, 0.3851, 0.7180, 0.2052, 0.3957, 0.5808, 0.1698, 0.8906, 0.0961,
         0.1576, 0.6826, 0.1933, 0.8078, 0.6731, 0.6201, 0.1704, 0.7303, 0.4715,
         0.4375, 0.7565, 0.5594, 0.1796, 0.2615, 0.1866, 0.6286, 0.4785, 0.9504,
         0.1650, 0.6815, 0.6451, 0.0425, 0.3692, 0.0742, 0.7326, 0.7904, 0.2136,
         0.1404, 0.9761, 0.9162]])

In [105]:
#flatten way2
t.reshape(-1)

tensor([0.9869, 0.7053, 0.9614, 0.5747, 0.4070, 0.6991, 0.1532, 0.9386, 0.4735,
        0.7032, 0.3851, 0.7180, 0.2052, 0.3957, 0.5808, 0.1698, 0.8906, 0.0961,
        0.1576, 0.6826, 0.1933, 0.8078, 0.6731, 0.6201, 0.1704, 0.7303, 0.4715,
        0.4375, 0.7565, 0.5594, 0.1796, 0.2615, 0.1866, 0.6286, 0.4785, 0.9504,
        0.1650, 0.6815, 0.6451, 0.0425, 0.3692, 0.0742, 0.7326, 0.7904, 0.2136,
        0.1404, 0.9761, 0.9162])

In [106]:
#flatten way3
t.view(t.numel())

tensor([0.9869, 0.7053, 0.9614, 0.5747, 0.4070, 0.6991, 0.1532, 0.9386, 0.4735,
        0.7032, 0.3851, 0.7180, 0.2052, 0.3957, 0.5808, 0.1698, 0.8906, 0.0961,
        0.1576, 0.6826, 0.1933, 0.8078, 0.6731, 0.6201, 0.1704, 0.7303, 0.4715,
        0.4375, 0.7565, 0.5594, 0.1796, 0.2615, 0.1866, 0.6286, 0.4785, 0.9504,
        0.1650, 0.6815, 0.6451, 0.0425, 0.3692, 0.0742, 0.7326, 0.7904, 0.2136,
        0.1404, 0.9761, 0.9162])

In [107]:
t.flatten()

tensor([0.9869, 0.7053, 0.9614, 0.5747, 0.4070, 0.6991, 0.1532, 0.9386, 0.4735,
        0.7032, 0.3851, 0.7180, 0.2052, 0.3957, 0.5808, 0.1698, 0.8906, 0.0961,
        0.1576, 0.6826, 0.1933, 0.8078, 0.6731, 0.6201, 0.1704, 0.7303, 0.4715,
        0.4375, 0.7565, 0.5594, 0.1796, 0.2615, 0.1866, 0.6286, 0.4785, 0.9504,
        0.1650, 0.6815, 0.6451, 0.0425, 0.3692, 0.0742, 0.7326, 0.7904, 0.2136,
        0.1404, 0.9761, 0.9162])

tutorial [here](https://www.youtube.com/watch?v=stWU37L91Yc&t=739s)

In [11]:
import torch
from torchvision import models
import torch.nn as nn

In [12]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6,12,5)
        
        self.fc1 = nn.Linear(12*4*4,120)
        self.fc2 = nn.Linear(120,60)
        self.out = nn.Linear(60,10)
        
    def forward(x):
        return x

In [13]:
network = Network()

In [14]:
print(network)

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)


Noteice here that thought we gavve kernel size is just 5, internally it is like a tuple of (5,5) representing the shape of filter. Also notice here that stride is (1,1), though we didnt give anything in code. By default stride is 1. and in (1,1), first one is for moving 1 stride left, other 1 for moving 1 down.

In [15]:
print(network.conv1)

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))


In [16]:
print(network.conv2)

Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))


In [17]:
print(network.fc1)

Linear(in_features=192, out_features=120, bias=True)


In [18]:
print(network.fc2)

Linear(in_features=120, out_features=60, bias=True)


In [19]:
print(network.out)

Linear(in_features=60, out_features=10, bias=True)


In [20]:
print(network.conv1.weight)

Parameter containing:
tensor([[[[-0.0571,  0.0678,  0.0539, -0.0469, -0.1322],
          [ 0.1886, -0.1164,  0.0810, -0.0857, -0.0408],
          [-0.0064, -0.0271,  0.0505,  0.0172, -0.1112],
          [ 0.1092,  0.1348,  0.0199, -0.0546,  0.0686],
          [ 0.1281,  0.1110, -0.0227,  0.1108,  0.1952]]],


        [[[ 0.0372, -0.0004,  0.0626,  0.1974, -0.0649],
          [ 0.0471, -0.0841,  0.0950,  0.0936,  0.1080],
          [-0.1308, -0.1270,  0.1296, -0.1837,  0.1346],
          [-0.1614,  0.1111,  0.0014,  0.1656, -0.0430],
          [-0.0921,  0.0779,  0.1964,  0.1505,  0.1319]]],


        [[[-0.1364,  0.1240, -0.0711,  0.1910,  0.1127],
          [-0.0152,  0.0606,  0.1458, -0.1553,  0.0575],
          [ 0.1572,  0.1410,  0.0063, -0.1345,  0.1978],
          [-0.0341, -0.1867, -0.1984,  0.0488,  0.0355],
          [ 0.1386,  0.1060, -0.0771, -0.0254,  0.0363]]],


        [[[-0.0991,  0.1674,  0.0653,  0.1194,  0.0218],
          [ 0.1741,  0.0187, -0.1611, -0.0637,  0.1997

In [21]:
print(network.conv1.weight.shape)

torch.Size([6, 1, 5, 5])


The above parameters/weights are learned as we train the Network in such a way that the loss function is minimized.

The parameter class keeps track of all the weights in network.

In [23]:
#self.conv2  = nn.Conv2d(6,12,5)
print(network.conv2.weight.shape)

torch.Size([12, 6, 5, 5])


In [24]:
print(network.fc1.weight.shape)

torch.Size([120, 192])


In [25]:
print(network.fc2.weight.shape)

torch.Size([60, 120])


In [26]:
print(network.out.weight.shape)

torch.Size([10, 60])


In [27]:
print(network.parameters)

<bound method Module.parameters of Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)>


In [28]:
for param in network.parameters():
    print(param.shape)

torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([12, 6, 5, 5])
torch.Size([12])
torch.Size([120, 192])
torch.Size([120])
torch.Size([60, 120])
torch.Size([60])
torch.Size([10, 60])
torch.Size([10])


In [29]:
for name, param in network.named_parameters():
    print(name,  '\t\t', param.shape)

conv1.weight 		 torch.Size([6, 1, 5, 5])
conv1.bias 		 torch.Size([6])
conv2.weight 		 torch.Size([12, 6, 5, 5])
conv2.bias 		 torch.Size([12])
fc1.weight 		 torch.Size([120, 192])
fc1.bias 		 torch.Size([120])
fc2.weight 		 torch.Size([60, 120])
fc2.bias 		 torch.Size([60])
out.weight 		 torch.Size([10, 60])
out.bias 		 torch.Size([10])


#### Forward operation 
-- from [here](https://www.youtube.com/watch?v=MasG7tZj-hw&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=21)

In [108]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6,12,5)
        
        self.fc1 = nn.Linear(12*4*4,120)
        self.fc2 = nn.Linear(120,60)
        self.out = nn.Linear(60,10)
        
    def forward(x):
        #(1) input layer
        x=x
        
        #(2) hidden conv layer
        x = self.conv1(x)
        x = F.relu(x)
        x = F.max_pool2d(x,kernel_size = 2,stride = 2)
        
        #(3) hidden conv layer
        x = self.conv2(x)
        x = F.relu(x)
        x = F.max_pool2d(x,kernel_size = 2,stride = 2)
        
        #(4)hidden linear layer
        x = x.reshape(-1,12*4*4)
        x = self.fc1(x)
        x = F.relu(x)
        
        #(5)hidden Linear layer
        x = self.fc2(x)
        x = F.relu(x)
        
        #(6)output layer
        x = self.out(x)
        #x = F.softmax(x,dim=1)
        '''We are not using softmax here, because of the loss function. CrossEntropyLoss function implicitly performs softmax operation'''
        
        return x

Both the relu and max pool are just pure operations and neither of them has weights, hence we call them from **functional** with F

and also remember that convolution1 is a combination of Convolution layer and 3 operations named convolution, relu, maxpool -- from [here](https://www.youtube.com/watch?v=MasG7tZj-hw&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=21)

with all hidden layer, people often use **ReLU**

## [Hyper parameter training in Deep learning](https://www.youtube.com/watch?v=ycxulUVoNbk&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=30)

#### you should always apply ReLU first and then Max-Pool later

from [here](https://discuss.pytorch.org/t/example-on-how-to-use-batch-norm/216), observe the below one

```self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_bn = nn.BatchNorm2d(20)
        self.dense1 = nn.Linear(in_features=320, out_features=50)
        self.dense1_bn = nn.BatchNorm1d(50)```

- Value inside **Batch Normalization** realted to the **outputsize of Conv** layers. 

- And also notice that for **Conv** Layer its **BatchNorm2d** and for **Linear** layer its **BatchNorm1d**.

- BatchNorm will only update the running averages in train mode, so if you want the model to keep updating them in test time, you will have to keep BatchNorm modules in the training mode. See the C implementation 670 for details (it should be readable).-- from [here](https://discuss.pytorch.org/t/example-on-how-to-use-batch-norm/216/3)